using System;

namespace RTS.Network;

public sealed record SessionInfo(
    string SessionName,
    string HostName,
    string Address,
    int Port);

public enum DiscoveryMessageType
{
    Discover,
    Advertise
}

public sealed record DiscoveryMessage(
    DiscoveryMessageType Type,
    string? SessionName = null,
    string? HostName = null,
    int Port = 0);

public enum NetworkMessageType
{
    JoinSession,
    JoinAccepted,
    JoinRejected,
    MemberJoined,
    MemberLeft,
    CommandToHost,
    CommandToMember,
    CommandToAll,
    SpawnRequest,
    SpawnCommand,
    GotoRequest,
    GotoCommand,
    StopRequest,
    StopCommand,
    AttackRequest,
    AttackCommand,
    ProjectileSpawnCommand,
    ProjectileImpactCommand,
    BulletImpactCommand,
    AttackTargetRequest,
    AttackTargetCommand,
    AttackGroundRequest,
    AttackGroundCommand,
    FollowRequest,
    FollowCommand,
    TemporaryTargetCommand,
    UnitHitCommand,
    DestroyUnitCommand,
    TextRequest,
    TextMessage,
    Error,
    ToolActionRequest,
    ToolActionCommand,
    RequestWorldData,
    WorldData,
    RequestPlayerUpdate,
    PlayerUpdate,
    BuildRequest,
    BuildCommand,
    BuildConstructionRequest,
    BuildConstructionCommand,
    TrainUnitRequest,
    TrainUnitCommand,
    EnterUnitRequest,
    EnterUnitCommand,
    EmbarkUnitCommand,
    LeaveContainerRequest,
    LeaveContainerCommand,
    UnitStateCommand,
    NotifyUnitsSelected,
    GrantArmyControlRequest,
    GrantArmyControlCommand,
    RevokeArmyControlRequest,
    RevokeArmyControlCommand,
    TransferUnitRequest,
    TransferUnitCommand,
    MergeArmiesRequest,
    MergeArmiesCommand,
    SetRallyPointRequest,
    SetRallyPointCommand,
    EarthworkRequest,
    EarthworkStartCommand,
    EarthworkCellCommand,
    EarthworkEndCommand,
    HelicopterOrderRequest,
    TiberiumSeedCommand
}

public sealed record WorldData(
    int Width,
    int Height,
    byte[] TileMap,
    float[] HeightMap,
    GameplayMarkerState[]? GameplayMarkers = null,
    TiberiumSeedState[]? TiberiumCells = null,
    MapObjectState[]? MapObjects = null);

public sealed record NetworkMessage(
    NetworkMessageType Type,
    Guid SenderId,
    Guid? TargetId = null,
    string? Command = null,
    string[]? Arguments = null,
    string? DisplayName = null,
    Guid? SessionId = null,
    string? Error = null,
    string? Text = null,
    Guid? PlayerId = null,
    Guid? UnitId = null,
    Guid[]? UnitIds = null,
    Guid? ConstructionSiteId = null,
    UnitState? UnitState = null,
    float Damage = 0.0f,
    float HitPoints = 0.0f,
    string? UnitTypeId = null,
    float TargetAngleY = 0.0f,
    float X = 0.0f,
    float Y = 0.0f,
    float Z = 0.0f,
    ToolShape? ToolShape = null,
    int ToolSize = 0,
    UnitAction? Action = null,
    TerrainTile? TerrainTile = null,
    WorldData? WorldData = null,
    int TeamId = 0,
    int? PlayerSkin = null,
    uint SelectionRevision = 0,
    Guid? ArmyId = null,
    Guid? SecondaryArmyId = null,
    Guid? ProductionOrderId = null,
    Guid? SpawnSourceBuildingId = null,
    float ProductionSeconds = 0.0f,
    float ExitX = 0.0f,
    float ExitY = 0.0f,
    float ExitZ = 0.0f,
    Guid? DriverUnitId = null,
    OccupantRole? OccupantRole = null,
    Guid? ProjectileId = null,
    ProjectileKind? ProjectileKind = null,
    float VelocityX = 0.0f,
    float VelocityY = 0.0f,
    float VelocityZ = 0.0f,
    float NormalX = 0.0f,
    float NormalY = 0.0f,
    float NormalZ = 0.0f,
    double ServerTime = 0.0,
    RallyPointState? RallyPoint = null,
    EarthworkOrder? EarthworkOrder = null,
    EarthworkKind? EarthworkKind = null,
    Guid? EarthworkOrderId = null,
    int EarthworkSequence = 0,
    int CellX = 0,
    int CellZ = 0,
    int[]? EarthworkCells = null,
    HelicopterOrder? HelicopterOrder = null,
    TiberiumSeedState? TiberiumSeed = null);
